/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.keole.stock;

public final class R {
    public static final class array {
        public static final int country_codes=0x7f0b0001;
        public static final int xwalk_resources_list=0x7f0b0000;
    }
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int select_dialog_multichoice=0x7f010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int select_dialog_singlechoice=0x7f010001;
    }
    public static final class color {
        public static final int color_picker_background_color=0x7f070001;
        public static final int color_picker_border_color=0x7f070000;
        public static final int contents_text=0x7f070004;
        public static final int dropdown_dark_divider_color=0x7f070003;
        public static final int dropdown_divider_color=0x7f070002;
        public static final int encode_view=0x7f070005;
        public static final int possible_result_points=0x7f070006;
        /**  Android standard ICS color 
         */
        public static final int result_minor_text=0x7f070007;
        public static final int result_points=0x7f070008;
        /**  Android standard ICS color 
         */
        public static final int result_text=0x7f070009;
        public static final int result_view=0x7f07000a;
        public static final int status_text=0x7f07000b;
        public static final int transparent=0x7f07000c;
        public static final int viewfinder_laser=0x7f07000d;
        /**  Android standard ICS color 
         */
        public static final int viewfinder_mask=0x7f07000e;
    }
    public static final class dimen {
        public static final int color_button_height=0x7f080002;
        /** 
         14.5 = Seekbar thumb width - border width, but it depends on the width
	     of the seek bar icon.
    
         */
        public static final int color_picker_gradient_margin=0x7f080001;
        /** 
         Fallback values if the corresponding com.android.internal.R dimensions
         cannot be retrieved by name.
         Note: Constants taken directly from Android's core/res/values/config.xml.
    
         */
        public static final int config_min_scaling_span=0x7f080005;
        public static final int config_min_scaling_touch_major=0x7f080006;
        public static final int dropdown_item_divider_height=0x7f080004;
        public static final int dropdown_item_height=0x7f080003;
        public static final int half_padding=0x7f080008;
        /**  Link Preview dimensions 
         */
        public static final int link_preview_overlay_radius=0x7f080000;
        public static final int standard_padding=0x7f080007;
    }
    public static final class drawable {
        public static final int bubble=0x7f020000;
        public static final int bubble_arrow_up=0x7f020001;
        public static final int color_button_background=0x7f020002;
        public static final int color_picker_advanced_select_handle=0x7f020003;
        public static final int color_picker_border=0x7f020004;
        public static final int dropdown_popup_background=0x7f020005;
        public static final int dropdown_popup_background_down=0x7f020006;
        public static final int dropdown_popup_background_up=0x7f020007;
        public static final int ic_menu_search_holo_light=0x7f020008;
        public static final int ic_menu_share_holo_light=0x7f020009;
        public static final int icon=0x7f02000a;
        public static final int launcher_icon=0x7f02000b;
        public static final int ondemand_overlay=0x7f02000c;
        public static final int pageinfo_warning_major=0x7f02000d;
        public static final int screen=0x7f02000e;
        public static final int share_via_barcode=0x7f02000f;
        public static final int shopper_icon=0x7f020010;
        public static final int splash=0x7f020011;
    }
    public static final class id {
        public static final int ampm=0x7f0a0038;
        public static final int appView=0x7f0a0031;
        public static final int arrow_image=0x7f0a0049;
        public static final int back_button=0x7f0a002d;
        public static final int barcode_image_view=0x7f0a000d;
        public static final int bookmark_title=0x7f0a0008;
        public static final int bookmark_url=0x7f0a0009;
        public static final int color_button_swatch=0x7f0a004c;
        public static final int color_picker_advanced=0x7f0a001c;
        public static final int color_picker_simple=0x7f0a001d;
        public static final int contents_supplement_text_view=0x7f0a0014;
        public static final int contents_text_view=0x7f0a0013;
        public static final int date_picker=0x7f0a0023;
        public static final int date_time_suggestion=0x7f0a0025;
        public static final int date_time_suggestion_label=0x7f0a0027;
        public static final int date_time_suggestion_value=0x7f0a0026;
        public static final int decode=0x7f0a0001;
        public static final int decode_failed=0x7f0a0002;
        public static final int decode_succeeded=0x7f0a0003;
        public static final int done_button=0x7f0a002e;
        public static final int dropdown_label=0x7f0a0029;
        public static final int dropdown_menu_text=0x7f0a0028;
        public static final int dropdown_popup_window=0x7f0a0000;
        public static final int dropdown_sublabel=0x7f0a002a;
        public static final int format_text_view=0x7f0a000e;
        public static final int gradient=0x7f0a001a;
        public static final int gradient_border=0x7f0a0019;
        public static final int help_contents=0x7f0a002c;
        public static final int history_detail=0x7f0a0030;
        public static final int history_title=0x7f0a002f;
        public static final int hour=0x7f0a0032;
        public static final int icon_view=0x7f0a0047;
        public static final int image_view=0x7f0a002b;
        public static final int launch_product_query=0x7f0a0004;
        public static final int main_text=0x7f0a004a;
        public static final int menu_history_clear_text=0x7f0a004e;
        public static final int menu_history_send=0x7f0a004d;
        public static final int meta_text_view=0x7f0a0012;
        public static final int meta_text_view_label=0x7f0a0011;
        public static final int milli=0x7f0a0037;
        public static final int minute=0x7f0a0033;
        public static final int more_colors_button=0x7f0a001f;
        public static final int more_colors_button_border=0x7f0a001e;
        public static final int page_number_view=0x7f0a003c;
        public static final int pickers=0x7f0a0043;
        public static final int position_in_year=0x7f0a0044;
        public static final int preview_view=0x7f0a000a;
        public static final int query_button=0x7f0a003a;
        public static final int query_text_view=0x7f0a0039;
        public static final int quit=0x7f0a0005;
        public static final int restart_preview=0x7f0a0006;
        public static final int result_button_view=0x7f0a0015;
        public static final int result_list_view=0x7f0a003b;
        public static final int result_view=0x7f0a000c;
        public static final int return_scan_result=0x7f0a0007;
        public static final int second=0x7f0a0035;
        public static final int second_colon=0x7f0a0034;
        public static final int second_dot=0x7f0a0036;
        public static final int seek_bar=0x7f0a001b;
        public static final int select_action_menu_copy=0x7f0a0051;
        public static final int select_action_menu_cut=0x7f0a0050;
        public static final int select_action_menu_paste=0x7f0a0052;
        public static final int select_action_menu_select_all=0x7f0a004f;
        public static final int select_action_menu_share=0x7f0a0053;
        public static final int select_action_menu_web_search=0x7f0a0054;
        public static final int selected_color_view=0x7f0a0022;
        public static final int selected_color_view_border=0x7f0a0021;
        public static final int share_app_button=0x7f0a003e;
        public static final int share_bookmark_button=0x7f0a003f;
        public static final int share_clipboard_button=0x7f0a0041;
        public static final int share_contact_button=0x7f0a0040;
        public static final int share_text_view=0x7f0a0042;
        public static final int shopper_button=0x7f0a0016;
        public static final int snippet_view=0x7f0a003d;
        public static final int status_view=0x7f0a0017;
        public static final int sub_text=0x7f0a004b;
        public static final int text=0x7f0a0018;
        public static final int text_wrapper=0x7f0a0048;
        public static final int time_picker=0x7f0a0024;
        public static final int time_text_view=0x7f0a0010;
        public static final int title=0x7f0a0020;
        public static final int top_view=0x7f0a0046;
        public static final int type_text_view=0x7f0a000f;
        public static final int viewfinder_view=0x7f0a000b;
        public static final int year=0x7f0a0045;
    }
    public static final class layout {
        public static final int bookmark_picker_list_item=0x7f030000;
        public static final int capture=0x7f030001;
        public static final int color_picker_advanced_component=0x7f030002;
        public static final int color_picker_dialog_content=0x7f030003;
        public static final int color_picker_dialog_title=0x7f030004;
        public static final int date_time_picker_dialog=0x7f030005;
        public static final int date_time_suggestion=0x7f030006;
        public static final int dropdown_item=0x7f030007;
        public static final int encode=0x7f030008;
        public static final int help=0x7f030009;
        public static final int history_list_item=0x7f03000a;
        public static final int main=0x7f03000b;
        public static final int multi_field_time_picker_dialog=0x7f03000c;
        public static final int search_book_contents=0x7f03000d;
        public static final int search_book_contents_header=0x7f03000e;
        public static final int search_book_contents_list_item=0x7f03000f;
        public static final int share=0x7f030010;
        public static final int two_field_date_picker=0x7f030011;
        public static final int validation_message_bubble=0x7f030012;
    }
    public static final class menu {
        public static final int capture=0x7f0c0000;
        public static final int encode=0x7f0c0001;
        public static final int history=0x7f0c0002;
        public static final int select_action_menu=0x7f0c0003;
    }
    public static final class raw {
        public static final int beep=0x7f050000;
        public static final int contacts_api=0x7f050001;
        public static final int device_capabilities_api=0x7f050002;
        public static final int icudtl=0x7f050003;
        public static final int launch_screen_api=0x7f050004;
        public static final int messaging_api=0x7f050005;
        public static final int presentation_api=0x7f050006;
        public static final int xwalk=0x7f050007;
    }
    public static final class string {
        public static final int accessibility_content_view=0x7f060002;
        public static final int accessibility_date_picker_month=0x7f06001e;
        public static final int accessibility_date_picker_week=0x7f060022;
        public static final int accessibility_date_picker_year=0x7f06001f;
        public static final int accessibility_datetime_picker_date=0x7f060030;
        public static final int accessibility_datetime_picker_time=0x7f060031;
        public static final int accessibility_time_picker_ampm=0x7f06002b;
        public static final int accessibility_time_picker_hour=0x7f060027;
        public static final int accessibility_time_picker_milli=0x7f06002a;
        public static final int accessibility_time_picker_minute=0x7f060028;
        public static final int accessibility_time_picker_second=0x7f060029;
        public static final int actionbar_share=0x7f060000;
        public static final int actionbar_web_search=0x7f060001;
        public static final int activity_name=0x7f060049;
        public static final int app_name=0x7f060046;
        /**  <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">QRコードスキャナー</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">סורק ברקודים</string> 
 <string name="app_name">Баркод Скенер</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">बारकोड स्कैनर</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">바코드 스캐너</string> 
 <string name="app_name">ماسح الرمز الشريطي</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barkod Tarayıcısı</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barra-kode Eskanerra</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Сканер штрих-кодов</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">סורק ברקודים</string> 
 <string name="app_name">条码扫描器</string> 
 <string name="app_name">條碼掃描器</string> 
         */
        public static final int app_picker_name=0x7f06004a;
        public static final int bookmark_picker_name=0x7f06004b;
        public static final int button_add_calendar=0x7f06004c;
        public static final int button_add_contact=0x7f06004d;
        public static final int button_back=0x7f06004e;
        public static final int button_book_search=0x7f06004f;
        public static final int button_cancel=0x7f060050;
        public static final int button_custom_product_search=0x7f060051;
        public static final int button_dial=0x7f060052;
        public static final int button_done=0x7f060053;
        public static final int button_email=0x7f060054;
        public static final int button_get_directions=0x7f060055;
        public static final int button_google_shopper=0x7f060056;
        public static final int button_mms=0x7f060057;
        public static final int button_ok=0x7f060058;
        public static final int button_open_browser=0x7f060059;
        public static final int button_product_search=0x7f06005a;
        public static final int button_search_book_contents=0x7f06005b;
        public static final int button_share_app=0x7f06005c;
        public static final int button_share_bookmark=0x7f06005d;
        public static final int button_share_by_email=0x7f06005e;
        public static final int button_share_by_sms=0x7f06005f;
        public static final int button_share_clipboard=0x7f060060;
        public static final int button_share_contact=0x7f060061;
        public static final int button_show_map=0x7f060062;
        public static final int button_sms=0x7f060063;
        public static final int button_web_search=0x7f060064;
        public static final int button_wifi=0x7f060065;
        public static final int color_picker_button_black=0x7f06001b;
        public static final int color_picker_button_blue=0x7f060017;
        public static final int color_picker_button_cancel=0x7f060013;
        public static final int color_picker_button_cyan=0x7f060016;
        public static final int color_picker_button_green=0x7f060018;
        public static final int color_picker_button_magenta=0x7f060019;
        public static final int color_picker_button_more=0x7f06000e;
        public static final int color_picker_button_red=0x7f060015;
        public static final int color_picker_button_set=0x7f060012;
        public static final int color_picker_button_white=0x7f06001c;
        public static final int color_picker_button_yellow=0x7f06001a;
        public static final int color_picker_dialog_title=0x7f060014;
        public static final int color_picker_hue=0x7f06000f;
        public static final int color_picker_saturation=0x7f060010;
        public static final int color_picker_value=0x7f060011;
        public static final int contents_contact=0x7f060066;
        public static final int contents_email=0x7f060067;
        public static final int contents_location=0x7f060068;
        public static final int contents_phone=0x7f060069;
        public static final int contents_sms=0x7f06006a;
        public static final int contents_text=0x7f06006b;
        public static final int copy_to_clipboard_failure_message=0x7f06001d;
        public static final int cpu_arch_mismatch_message=0x7f060043;
        public static final int cpu_arch_mismatch_title=0x7f060042;
        public static final int date_picker_dialog_clear=0x7f060034;
        public static final int date_picker_dialog_other_button_label=0x7f060032;
        public static final int date_picker_dialog_set=0x7f060020;
        public static final int date_picker_dialog_title=0x7f060033;
        public static final int date_time_picker_dialog_title=0x7f06002f;
        public static final int download_already_exists_toast=0x7f06003a;
        public static final int download_failed_toast=0x7f06003b;
        public static final int download_finished_toast=0x7f06003c;
        public static final int download_no_permission_toast=0x7f060039;
        public static final int download_start_toast=0x7f060038;
        public static final int go=0x7f060047;
        public static final int goto_store_button_label=0x7f060044;
        public static final int history_clear_one_history_text=0x7f06006d;
        public static final int history_clear_text=0x7f06006c;
        public static final int history_email_title=0x7f06006e;
        public static final int history_empty=0x7f06006f;
        public static final int history_empty_detail=0x7f060070;
        public static final int history_send=0x7f060071;
        public static final int history_title=0x7f060072;
        public static final int http_auth_log_in=0x7f060041;
        public static final int http_auth_password=0x7f060040;
        public static final int http_auth_title=0x7f06003e;
        public static final int http_auth_user_name=0x7f06003f;
        public static final int js_alert_title=0x7f060035;
        public static final int js_confirm_title=0x7f060036;
        public static final int js_prompt_title=0x7f060037;
        public static final int launcher_name=0x7f060048;
        public static final int low_memory_error=0x7f06000c;
        public static final int media_player_error_button=0x7f060006;
        public static final int media_player_error_text_invalid_progressive_playback=0x7f060004;
        public static final int media_player_error_text_unknown=0x7f060005;
        public static final int media_player_error_title=0x7f060003;
        public static final int media_player_loading_video=0x7f060007;
        public static final int menu_encode_mecard=0x7f060073;
        public static final int menu_encode_vcard=0x7f060074;
        public static final int menu_help=0x7f060075;
        public static final int menu_history=0x7f060076;
        public static final int menu_settings=0x7f0600c1;
        public static final int menu_share=0x7f060077;
        public static final int month_picker_dialog_title=0x7f060021;
        public static final int msg_bulk_mode_scanned=0x7f060078;
        public static final int msg_camera_framework_bug=0x7f060079;
        public static final int msg_default_format=0x7f06007a;
        public static final int msg_default_meta=0x7f06007b;
        public static final int msg_default_mms_subject=0x7f06007c;
        public static final int msg_default_status=0x7f06007d;
        public static final int msg_default_time=0x7f06007e;
        public static final int msg_default_type=0x7f06007f;
        public static final int msg_encode_contents_failed=0x7f060080;
        public static final int msg_google_books=0x7f060081;
        public static final int msg_google_product=0x7f060082;
        public static final int msg_google_shopper_missing=0x7f060083;
        public static final int msg_install_google_shopper=0x7f060084;
        public static final int msg_intent_failed=0x7f060085;
        public static final int msg_redirect=0x7f060086;
        public static final int msg_sbc_book_not_searchable=0x7f060087;
        public static final int msg_sbc_failed=0x7f060088;
        public static final int msg_sbc_no_page_returned=0x7f060089;
        public static final int msg_sbc_page=0x7f06008a;
        public static final int msg_sbc_results=0x7f06008b;
        public static final int msg_sbc_searching_book=0x7f06008c;
        public static final int msg_sbc_snippet_unavailable=0x7f06008d;
        public static final int msg_sbc_unknown_page=0x7f06008e;
        public static final int msg_share_explanation=0x7f06008f;
        public static final int msg_share_subject_line=0x7f060090;
        public static final int msg_share_text=0x7f060091;
        public static final int msg_sure=0x7f060092;
        public static final int msg_unmount_usb=0x7f060093;
        public static final int opening_file_error=0x7f06000d;
        public static final int preferences_actions_title=0x7f060094;
        public static final int preferences_auto_focus_title=0x7f060095;
        public static final int preferences_bulk_mode_summary=0x7f060096;
        public static final int preferences_bulk_mode_title=0x7f060097;
        public static final int preferences_copy_to_clipboard_title=0x7f060098;
        public static final int preferences_custom_product_search_summary=0x7f060099;
        public static final int preferences_custom_product_search_title=0x7f06009a;
        public static final int preferences_decode_1D_title=0x7f06009b;
        public static final int preferences_decode_Data_Matrix_title=0x7f06009c;
        public static final int preferences_decode_QR_title=0x7f06009d;
        public static final int preferences_device_bug_workarounds_title=0x7f06009e;
        public static final int preferences_disable_continuous_focus_summary=0x7f06009f;
        public static final int preferences_disable_continuous_focus_title=0x7f0600a0;
        public static final int preferences_disable_exposure_title=0x7f0600a1;
        public static final int preferences_front_light_summary=0x7f0600a2;
        public static final int preferences_front_light_title=0x7f0600a3;
        public static final int preferences_general_title=0x7f0600a4;
        public static final int preferences_name=0x7f0600a5;
        public static final int preferences_play_beep_title=0x7f0600a6;
        public static final int preferences_remember_duplicates_summary=0x7f0600a7;
        public static final int preferences_remember_duplicates_title=0x7f0600a8;
        public static final int preferences_result_title=0x7f0600a9;
        public static final int preferences_scanning_title=0x7f0600aa;
        public static final int preferences_search_country=0x7f0600ab;
        public static final int preferences_supplemental_summary=0x7f0600ae;
        public static final int preferences_supplemental_title=0x7f0600af;
        public static final int preferences_try_bsplus=0x7f0600ac;
        public static final int preferences_try_bsplus_summary=0x7f0600ad;
        public static final int preferences_vibrate_title=0x7f0600b0;
        public static final int profiler_error_toast=0x7f06000b;
        public static final int profiler_no_storage_toast=0x7f06000a;
        public static final int profiler_started_toast=0x7f060008;
        public static final int profiler_stopped_toast=0x7f060009;
        public static final int report_feedback_button_label=0x7f060045;
        public static final int result_address_book=0x7f0600b1;
        public static final int result_calendar=0x7f0600b2;
        public static final int result_email_address=0x7f0600b3;
        public static final int result_geo=0x7f0600b4;
        public static final int result_isbn=0x7f0600b5;
        public static final int result_product=0x7f0600b6;
        public static final int result_sms=0x7f0600b7;
        public static final int result_tel=0x7f0600b8;
        public static final int result_text=0x7f0600b9;
        public static final int result_uri=0x7f0600ba;
        public static final int result_wifi=0x7f0600bb;
        public static final int sbc_name=0x7f0600bc;
        public static final int share_name=0x7f0600bd;
        public static final int ssl_alert_title=0x7f06003d;
        public static final int time_picker_dialog_am=0x7f060024;
        public static final int time_picker_dialog_hour_minute_separator=0x7f06002c;
        public static final int time_picker_dialog_minute_second_separator=0x7f06002d;
        public static final int time_picker_dialog_pm=0x7f060025;
        public static final int time_picker_dialog_second_subsecond_separator=0x7f06002e;
        public static final int time_picker_dialog_title=0x7f060026;
        public static final int week_picker_dialog_title=0x7f060023;
        public static final int wifi_changing_network=0x7f0600be;
        public static final int wifi_ssid_label=0x7f0600bf;
        public static final int wifi_type_label=0x7f0600c0;
    }
    public static final class style {
        public static final int DropdownPopupWindow=0x7f090001;
        public static final int SelectPopupDialog=0x7f090000;
    }
    public static final class xml {
        public static final int config=0x7f040000;
        public static final int preferences=0x7f040001;
    }
}
